### ISSUE TITLE
現在打牌是不是都要手動?

### ISSUE THREAD

**Issue by heatonxc** [ckx000/GBF#5]
把碼打到console 
只會自動保持牌 要手動按start 跟high low 
是不是我用錯法方法加載?

**Comment by ckx000** [comment]
模拟方式错了,试试使用另一个模拟手机的插件来模拟手机模式

**Comment by heatonxc** [comment]
嗯..從chrome換成firefox 可以了, 但是firefox顯示的UI 爆炸了..全都亂位了
